Files already downloaded and verified
Files already downloaded and verified
    step 0:
[64,3,32,32,]
[64,16,1,1,]
Training:   0%|                                                                                                                       | 0/10000 [00:43<?, ?it/s]
Traceback (most recent call last):
  File "models/WGAN.py", line 164, in <module>
    manager.train()
  File "models/WGAN.py", line 120, in train
    self.wandb_run.log({'lossD':loss.data.mean()}, step=i)
RuntimeError: [38m[f 0106 13:12:45.704505 32 executor.cc:686] 
[38mExecute fused operator(20/57) failed. 
[38m[JIT Source]: /home/zhouqianrui/.cache/jittor/jt1.3.8/g++8.5.0/py3.7.16/Linux-5.15.0-7xb0/IntelRXeonRPlax67/default/cu11.2.152_sm_70/jit/__opkey0_broadcast_to__Tx_float32__DIM_7__BCAST_19__opkey1_reindex__Tx_uint8__XDIM_4__YDIM___hash_e2118225335040_op.cc 
[38m[OP TYPE]: fused_op:( broadcast_to, reindex, binary.multiply, reduce.add,)
[38m[Input]: float32[16,3,4,4,], uint8[64,3,32,32,], 
[38m[Output]: float32[64,16,16,16,], 
[38m[Async Backtrace]: --- 
[38m     models/WGAN.py:164 <<module>> 
[38m     models/WGAN.py:110 <train> 
[38m     /home/zhouqianrui/anaconda3/envs/mc/lib/python3.7/site-packages/jittor/__init__.py:1172 <__call__> 
[38m     models/WGAN.py:58 <execute> 
[38m     /home/zhouqianrui/anaconda3/envs/mc/lib/python3.7/site-packages/jittor/__init__.py:1172 <__call__> 
[38m     /home/zhouqianrui/anaconda3/envs/mc/lib/python3.7/site-packages/jittor/nn.py:2202 <execute> 
[38m     /home/zhouqianrui/anaconda3/envs/mc/lib/python3.7/site-packages/jittor/__init__.py:1172 <__call__> 
[38m     /home/zhouqianrui/anaconda3/envs/mc/lib/python3.7/site-packages/jittor/nn.py:972 <execute> 
[38m[Reason]: could not create a descriptor for a dilated convolution forward propagation primitive
Traceback (most recent call last):
  File "models/WGAN.py", line 164, in <module>
    manager.train()
  File "models/WGAN.py", line 120, in train
    self.wandb_run.log({'lossD':loss.data.mean()}, step=i)
RuntimeError: [38m[f 0106 13:12:45.704505 32 executor.cc:686] 
[38mExecute fused operator(20/57) failed. 
[38m[JIT Source]: /home/zhouqianrui/.cache/jittor/jt1.3.8/g++8.5.0/py3.7.16/Linux-5.15.0-7xb0/IntelRXeonRPlax67/default/cu11.2.152_sm_70/jit/__opkey0_broadcast_to__Tx_float32__DIM_7__BCAST_19__opkey1_reindex__Tx_uint8__XDIM_4__YDIM___hash_e2118225335040_op.cc 
[38m[OP TYPE]: fused_op:( broadcast_to, reindex, binary.multiply, reduce.add,)
[38m[Input]: float32[16,3,4,4,], uint8[64,3,32,32,], 
[38m[Output]: float32[64,16,16,16,], 
[38m[Async Backtrace]: --- 
[38m     models/WGAN.py:164 <<module>> 
[38m     models/WGAN.py:110 <train> 
[38m     /home/zhouqianrui/anaconda3/envs/mc/lib/python3.7/site-packages/jittor/__init__.py:1172 <__call__> 
[38m     models/WGAN.py:58 <execute> 
[38m     /home/zhouqianrui/anaconda3/envs/mc/lib/python3.7/site-packages/jittor/__init__.py:1172 <__call__> 
[38m     /home/zhouqianrui/anaconda3/envs/mc/lib/python3.7/site-packages/jittor/nn.py:2202 <execute> 
[38m     /home/zhouqianrui/anaconda3/envs/mc/lib/python3.7/site-packages/jittor/__init__.py:1172 <__call__> 
[38m     /home/zhouqianrui/anaconda3/envs/mc/lib/python3.7/site-packages/jittor/nn.py:972 <execute> 
[38m[Reason]: could not create a descriptor for a dilated convolution forward propagation primitive